username_file: usernames.txt
vote_url_file: urls.txt
headless: "True"
# Fake useragent can cause problems
fake_useragent: "False"
proxy:
  enabled: "False"
  # Allowed types: HTTP, HTTPS, SOCKS
  type: SOCKS
  # If the type is SOCKS specify the version (4 or 5)
  socks_version: 4
  file: proxies.txt
use_timer: "True"
captcha_tries: 1
